name: {{ app_name }}
description: A new Flutter project.

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_db_store: ^5.0.0
  dio_cookie_manager: ^2.0.0
  elementary: ^1.5.0
  extended_image: ^6.3.2

  flutter:
    sdk: flutter

  package_info: ^2.0.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
